generated_videos_folder: './inference_samples/inference_samples_1'
real_videos_folder: './data/test_videos'
train_videos_folder: './data/train_videos'
clip_file_test: 'data/clip_file_test.txt'
clip_file_train_middle: 'data/clip_file_train_middle.txt'
clip_file_train_end: 'data/clip_file_train_end.txt'
prompts_file: './data/test_captions.txt'
height: 512
width: 512
frames_per_video: 20