pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
model_path: "./final_model/model-1"
prompt_file: "./data/test_captions.txt"
test_n: 1
inv_latent_path: "final_model/inv_latents/ddim_latent-500.pt"
frames_per_video: 20
height: 512
width: 512
inference_steps: 150
guidance_scale: 12.5
seed: 33