pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
model_path: "./final_model/model-1"
prompt_file: "./data/test_captions.txt"
train_prompts_file: "./data/train_captions.txt"
test_n: 1
frames_per_video: 20
height: 512
width: 512
inference_steps: 150
guidance_scale: 12.5